#DB CONFIGURATION
spring.datasource.url: jdbc:h2:file:/home/alkis/data/MathAsmScript/mathasmscript
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: mathasmscript
spring.datasource.password: logic123!

spring.h2.console.enabled: true
spring.h2.console.path: /h2


#LIQUIBASE
spring.liquibase.change-log: classpath:/db/changelog/changelog-master.xml


# GRAPHQL
graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
    # specification and expectations of most clients, so use this option with caution
    schema-parser-options.introspection-enabled: true

  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
